### ISSUE TITLE
repeat functionality seems broken

### ISSUE THREAD

**Issue by sriramkswamy** [mrkkrp/modalka#12]
I have bound the Emacs `repeat` function to `.`. Whenever I try to press `.` more than once, I get `Lisp nesting exceeds ‘max-lisp-eval-depth’`

**Comment by mrkkrp** [comment]
I can't reproduce that. Here is how I set up the `repeat` command:

```emacs-lisp
(define-key modalka-mode-map (kbd ".") #'repeat)
```

After that if I execute some command and press <kbd>.</kbd>, it's repeated. I can press it repeatedly and no problem whatsoever occurs.

**Comment by sriramkswamy** [comment]
I see. I just bind it to the already existing default Emacs binding.

```
(modalka-define-kbd "." "C-x z")
```

Is this not the right thing to do?

**Comment by mrkkrp** [comment]
Well what is happening in this case is perhaps that Modalka executes that `repeat` command, but the `repeat` command does not regard previous command executed as itself (because of wrappings) so next time it thinks “OK, previous command wasn't me, I can repeat it safely then”, and it tries to repeat the previous command that in turn tries to repeat command just before it, etc., sending Emacs into an infinite loop. I didn't check this though and I'm using a number of commands that check this “previous command” variable without problems. No time to dig deeply into this unless it really breaks something.

Please use the method I showed in this case :-)

**Comment by sriramkswamy** [comment]
Oh, I see. I understand. I'll close this issue, thanks.
