### ISSUE TITLE
Modalka overrides org-speed-commands-users

### ISSUE THREAD

**Issue by rsuhada** [mrkkrp/modalka#6]
Dear Mark,

is it possible to easily accomodate org-speed-commands along modalka?
Now modalka overrides them.

The speed commands a native very-lite modal keys active only in the very beggining of TODO headlines ([here](http://orgmode.org/manual/Speed-keys.html)). 

Just discovered your mode and it seems that it is a perfact match for me! Thank you!

**Comment by mrkkrp** [comment]
As I understand, you want certain keys that are translated by the package to behave differently when cursor is at the beginning of line and `org-speed-command` is not `nil`. This would be not easy to implement because `modalka-mode` is a minor mode and thus it overwrites major mode bindings.

Easiest solution would be to start in *insert mode* in Org buffers so you can use the speed commands and then enable/toggle `modalka-mode` manually as needed. See `README.md` for information about how to tell Modalka where it should be active by default.

**Comment by rsuhada** [comment]
Sounds good.. jumping out of modalka is easy enough, so this is fine. I've also disable it in the org-agenda buffers as you've suggested and this way it seems to work great. Thank you!

I'd also like to ask: would it be simple to implement a version of modalka-define-kbd, that would bind functions instead of keybindings?

e.g.: (modalka-define-kbd "n" 'next-line) instead of (modalka-define-kbd "n" "C-n")

The advantage for this is that you would not need to have same functions bound 2x (but you still could if you would like to).

In any case, I'm really happy I've discovered it, because I'm too dependent on my bindings to make the really big jump to evil mode and frankly the other options weren't very impressive. I think you did a great job of explaining the trade-offs in the README.

Thanks again!

**Comment by mrkkrp** [comment]
Glad you like it! Re, about binding commands: it would be quite easy, and maybe I'll add something like this in the future. I'll close the issue since it seems to be resolved now.

**Comment by mrkkrp** [comment]
By the way, it's simple to bind any command, because `modalka-mode` is just a normal minor mode, for example:

```emacs-lisp
(define-key modalka-mode-map (kbd "n") #'next-line)
```

So actually, no special function needed. Sorry that I didn't figure that out when you asked me :-)

**Comment by rsuhada** [comment]
Just now gotten around to try it. This is great, I've already refactored my config to bind directly to functions. Thank you for the help!
